import { Inter } from "next/font/google";
import "./globals.css";
import { Syne, Plus_Jakarta_Sans } from 'next/font/google'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import CartProviders from "./components/Provider";
import { Footer } from "./components/Footer";



const syne = Syne({
  weight: '700',
  subsets: ['latin'],
  variable: '--font-syne',

})
const syne2 = Syne({
  weight: '600',
  subsets: ['latin'],
  variable: '--font-syne2',

})
const jak = Plus_Jakarta_Sans({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-jak',

})

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${syne.variable} ${syne2.variable} ${jak.variable}`}>
      <body>
        <CartProviders>
          <div className="max-w-[100vw]">
          {children}

          </div>
        <Footer/>
        </CartProviders>
       </body>
    </html>
  );
}
